substitutions:
  _API_URL: 'https://corewebops-backend-190047453514.us-central1.run.app'
  _TAG: 'latest'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'VITE_API_URL=${_API_URL}',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/corewebops/frontend:${_TAG}',
      './frontend'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/corewebops/frontend:${_TAG}'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','corewebops-frontend',
        '--image','us-central1-docker.pkg.dev/$PROJECT_ID/corewebops/frontend:${_TAG}',
        '--region','us-central1',
        '--platform','managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/corewebops/frontend:${_TAG}'

