"""add_staff_permissions

Revision ID: f666e4fc8f3e
Revises: 22315a47111f
Create Date: 2026-02-12 12:09:22.485003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f666e4fc8f3e'
down_revision: Union[str, None] = '22315a47111f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_manage_inbox', sa.Boolean(), nullable=False),
    sa.Column('can_manage_bookings', sa.Boolean(), nullable=False),
    sa.Column('can_manage_forms', sa.Boolean(), nullable=False),
    sa.Column('can_view_inventory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_permissions_id'), 'staff_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_staff_permissions_user_id'), 'staff_permissions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_permissions_user_id'), table_name='staff_permissions')
    op.drop_index(op.f('ix_staff_permissions_id'), table_name='staff_permissions')
    op.drop_table('staff_permissions')
    # ### end Alembic commands ###
