"""add_booking_type

Revision ID: 46ff28dedce0
Revises: e3e3435b8ff6
Create Date: 2026-02-12 12:45:36.179501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ff28dedce0'
down_revision: Union[str, None] = 'e3e3435b8ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_types',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_types_id'), 'booking_types', ['id'], unique=False)
    op.create_index(op.f('ix_booking_types_workspace_id'), 'booking_types', ['workspace_id'], unique=False)
    op.add_column('bookings', sa.Column('booking_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_booking_type_id'), 'bookings', ['booking_type_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'booking_types', ['booking_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_booking_type_id'), table_name='bookings')
    op.drop_column('bookings', 'booking_type_id')
    op.drop_index(op.f('ix_booking_types_workspace_id'), table_name='booking_types')
    op.drop_index(op.f('ix_booking_types_id'), table_name='booking_types')
    op.drop_table('booking_types')
    # ### end Alembic commands ###
