"""expand_workspace_status

Revision ID: e3e3435b8ff6
Revises: f666e4fc8f3e
Create Date: 2026-02-12 12:40:47.256518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e3435b8ff6'
down_revision: Union[str, None] = 'f666e4fc8f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual enum expansion
    # Use autocommit block because ALTER TYPE cannot run inside a transaction block
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE workspace_status ADD VALUE IF NOT EXISTS 'email_connected'")
        op.execute("ALTER TYPE workspace_status ADD VALUE IF NOT EXISTS 'booking_configured'")
        op.execute("ALTER TYPE workspace_status ADD VALUE IF NOT EXISTS 'forms_linked'")
        op.execute("ALTER TYPE workspace_status ADD VALUE IF NOT EXISTS 'inventory_ready'")
        op.execute("ALTER TYPE workspace_status ADD VALUE IF NOT EXISTS 'staff_added'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
