"""add_manual_override

Revision ID: 0c0ed8bb4a2b
Revises: 46ff28dedce0
Create Date: 2026-02-12 13:07:43.976976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0ed8bb4a2b'
down_revision: Union[str, None] = '46ff28dedce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('manual_override', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'manual_override')
    # ### end Alembic commands ###
