"""create_internal_messages_global_table

Revision ID: 010c9facad0f
Revises: 16a04ce4293c
Create Date: 2026-02-25 23:32:58.128735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010c9facad0f'
down_revision: Union[str, None] = '16a04ce4293c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_alerts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('in_app_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('marketing_emails', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_preferences_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='notification_preferences_pkey')
    )
    # ### end Alembic commands ###
